config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_lists do
   resources :todo_items do
    member do
     patch :complete
    end
  end
end

  root "todo_lists#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  acts_as_list scope: :todo_list

  def completed?
   !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  # has_many :todo_items, :dependent => :destroy
  has_many :todo_items, -> { order(position: :asc) }, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: []
  before_action :todo_lists_url, only: []
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]

  def create
   @todo_item = @todo_list.todo_items.create(todo_item_params)
   redirect_to @todo_list
  end

  def destroy
   @todo_item = @todo_list.todo_items.find(params[:id])
   if @todo_item.destroy
    flash[:success] = "Todo List item was deleted."
   else
    flash[:error] = "Todo List item could not be deleted."
   end
   redirect_to @todo_list
  end

  def complete
   @todo_item.update_attribute(:completed_at, Time.now)
   redirect_to @todo_list, notice: "Todo item completed"
  end

  private

  def set_todo_list
   @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def todo_item_params
   params[:todo_item].permit(:content)
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
 <%= f.text_field :content, placeholder: "New Todo" %>
 <%= f.submit %>
<% end %>

app/views/layouts/_todo_item.html.erb
<div class="row clearfix">
 <% if todo_item.completed? %>
  <div class="complete">
   <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
    <i style="opacity: 0.4;" class="fa fa-check"></i>
   <% end %>
  </div>
  <div class="todo_item">
   <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
  </div>
  <div class="trash">
   <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash"></i>
   <% end %>
  </div>
 <% else %>
  <div class="complete">
   <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
    <i class="fa fa-circle-thin"></i>
   <% end %>
  </div>
  <div class="todo_item">
   <p><%= todo_item.content %></p>
  </div>
  <div class="trash">
   <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash"></i>
   <% end %>
  </div>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300;400;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom shadow-sm">
      <%= link_to icon('fas', 'list-ul', 'TodoList'), root_path, class: 'navbar-brand' %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <%= link_to icon('fas', 'home', 'Home'), todo_lists_path, class: 'nav-item nav-link' %>
          <%= link_to icon('fas', 'plus', 'Add List'), new_todo_list_path, class: 'nav-item nav-link mr-3' %>

          <%= link_to icon('fab', 'github', 'GitHub'), 'https://github.com/Leeroy6821/TodoList', target: "_blank", class: 'nav-item nav-link' %>
          <%= link_to icon('fab', 'gitlab', 'GitLab'), 'https://gitlab.com/Leeroy6821/todolist', target: "_blank", class: 'nav-item nav-link' %>
        </div>

        <% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-dark ml-md-4' %>
        <% else %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-dark ml-md-4' %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-dark ml-md-2' %>
        <% end %>
      </div>
    </nav>

    <header class="jumbotron text-center mb-5">
      <h1 class="text-dark">My Todo Lists</h1>
      <p class="lead">My example app ...</p>
    </header>

    <main class="container-fluid">
      <%= yield %>
    </main>

    <footer class="container-fluid mt-5 pt-4 pb-4 border-top">
      <p class="text-center text-muted"><%= icon('fas', 'list-ul', 'TodoList') %></p>
    </footer>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
 <%= f.text_field :content, placeholder: "New Todo" %>
 <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<% if todo_item.completed? %>

  <li class="list-group-item" style="opacity: 0.5">

    <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
      <strike class="mr-4 text-secondary">
        <%= icon('fas', 'check') %> <%= todo_item.content %>
      </strike>
    <% end %>
    <%= link_to icon('fas', 'times text-danger'), todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
  </li>

<% else %>

  <li class="list-group-item">
    <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch, class: 'text-info' do %>
      <%= icon('fas', 'check') %> <%= todo_item.content %>
    <% end %>
    <%= link_to icon('fas', 'times ml-4 text-danger'), todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
  </li>

<% end %>

app/views/todo_items/index.html.erb
<% @todo_lists.each do |todo_list| %>
<table class="table table-hover table-responsive-sm">
<div class="index_row clearfix">
  <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
  <p class="todo_list_sub_title"><%= todo_list.description %></p>
</div>
<% end %><div class="links">
  <%= link_to "New Todo List", new_todo_list_path %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
      <% if todo_list.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

          <ul>
            <% todo_list.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.text_field :title, placeholder: :title, class: "form-control form-control-lg" %>
      </div>

      <div class="form-group">
        <%= form.text_area :description, rows: '5', placeholder: 'Enter your text ...', class: "form-control form-control-lg" %>
      </div>

      <div class="actions">
        <%= form.submit class: "btn btn-dark btn-lg mb-5" %>
      </div>
    <% end %>
  </div>
</div>

app/views/todo_lists/edit.html.erb
<h2 class="mb-4">Editing Todo List</h2>

<%= render 'form', todo_list: @todo_list %>

<%= link_to icon('fas', 'arrow-left', 'Back'), todo_lists_path, class: 'btn btn-outline-secondary btn-lg' %>
<%= link_to icon('fas', 'eye', 'Show'), @todo_list, class: 'btn btn-outline-secondary btn-lg' %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to icon('fas', 'plus', 'New Todo List'), new_todo_list_path, class: 'btn btn-outline-dark btn-lg mb-5' %>


<div class="row">
  <% @todo_lists.each do |todo_list| %>
    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title"><%= todo_list.title %></h2>
          <p class="card-text"><%= todo_list.description %></p>
        </div>
        <div class="card-footer bg-transparent d-flex justify-content-between">
          <%= link_to icon('fas', 'eye', 'Show'), todo_list, class: 'text-body' %>
          <%= link_to icon('fas', 'edit', 'Edit'), edit_todo_list_path(todo_list), class: 'text-body' %>
          <%= link_to icon('fas', 'trash', 'Destroy'), todo_list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-body' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to icon('fas', 'plus', 'New Todo List'), new_todo_list_path, class: 'btn btn-outline-dark btn-lg mt-5' %>

app/views/todo_lists/new.html.erb
<div class="row justify-content-md-center">
  <div class="col-md-12">
    <h2 class="mb-4">New Todo List</h2>

  <%= render 'form', todo_list: @todo_list %>

  <%= link_to icon('fas', 'arrow-left', 'Back'), todo_lists_path, class: 'btn btn-outline-secondary btn-lg' %>
  </div>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="mb-4"><%= @todo_list.title %></h2>
<p class="lead"><%= @todo_list.description %></p>

<div id="todo_items_wrapper">

<ul class="list-group list-group-flush my-5">
  <%= render @todo_list.todo_items %>
</ul>

 <hr>

 <h3 class="mb-4">Create new item</h3>
 <div id="form">
  <%= render "todo_items/form" %>
 </div>
</div>

<div class="mt-5">
  <%= link_to icon('fas', 'arrow-left', 'Back'), todo_lists_path, class: 'btn btn-outline-secondary btn-lg' %>
  <%= link_to icon('fas', 'edit', 'Edit'), edit_todo_list_path(@todo_list), class: 'btn btn-outline-secondary  btn-lg' %>
  <%= link_to icon('fas', 'trash', 'Delete'), todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-secondary  btn-lg' %>
</div>